### ISSUE TITLE
Grouping queries by OR instead of AND - bad documentation

### ISSUE THREAD

**Issue by mightymatth** [activerecord-hackery/ransack#720] opened 2016-09-06 12:03 UTC
I was trying to merge queries on the way that is explained in documentation, but it did not work correctly. With this:

```
2.2.0 :005 > Spree::Associate.ransack("name_cont"=>"croatia-", "sku_cont"=>"croatia-", m: 'or')
```

I get `params` and `options` :

```
{"name_or_translations_name_cont"=>"croatia-", "sku_cont"=>"croatia-", "m_"=>"or"}
{}
```

and I get search response like this:

```
 => Ransack::Search
<class: Spree::Associate, base: Grouping 
<conditions: [Condition <attributes: ["name", "translations_name"], predicate: cont, combinator: or, values: ["croatia-"]>, Condition <attributes: ["sku"], predicate: cont, values: ["croatia-"]>]
, combinator: and>>
```

Firstly, I don't think that merge parameter in **m** should change to **m_** and I don't know why that happens. Secondly, as you can see, last combinator in response should be **or**, not **and**.

I looked into the code and made workaround with setting `grouping: 'or'` into the **options** section of **ransack** command. 

Now I get this and this is correct behavior:

```
2.2.0 :007 > Spree::Associate.ransack({"name_cont"=>"croatia-", "sku_cont"=>"croatia-"}, {grouping: 'or'})

{"name_or_translations_name_cont"=>"croatia-", "sku_cont"=>"croatia-"}
{:grouping=>"or"}

 => Ransack::Search
<class: Spree::Associate, base: Grouping 
<conditions: [Condition <attributes: ["name", "translations_name"], predicate: cont, combinator: or, values: ["croatia-"]>, Condition <attributes: ["sku"], predicate: cont, values: ["croatia-"]>],
 combinator: or>> 

```

The problem happens because there is bug with allias methods between `:m`, `:combinator` and `:grouping`. This line of code (`ransack-1.4.1/lib/ransack/search.rb`) is beginning of the issue. I think you will figure out what I'm talking about quickly.

**Comment by jonatack** [comment] 2016-10-10 19:56
Hi @mightymatth, I am unable to reproduce your issue.

Putting on my detective hat, it looks like you are using Ransack 1.4.1, an old version from more than 2 years ago, and you didn't say which versions of Ruby and Rails you are using with it. So it's difficult for someone to reproduce or guess your environment -- without trying all the possible combinations.

Did you verify that the problem exists with the current version of Ransack? If yes, could you please provide complete info to reproduce your issue? Please see CONTRIBUTING.md for more.

Closing for now, can re-open if you follow up. Thanks.

**Closed by jonatack** 2016-10-10 19:56 UTC
