### ISSUE TITLE
Ransack not working for boolean column

### ISSUE THREAD

**Issue by hoangnghiem** [activerecord-hackery/ransack#625] opened 2015-12-17 09:03 UTC
I have a boolean column named 'on_sale' on product model. According to https://github.com/activerecord-hackery/ransack/wiki/Basic-Searching#true, below code should works but it doesn't

```
2.2.1 :004 > Spree::Product.ransack(on_sale_true: '1').result.to_sql
 => "SELECT \"spree_products\".* FROM \"spree_products\" WHERE \"spree_products\".\"deleted_at\" IS NULL" 
```

![screen shot 2015-12-17 at 3 53 16 pm](https://cloud.githubusercontent.com/assets/62233/11865577/7aae8c96-a4d7-11e5-816a-26b25476fa96.png)

Am I missing something?

**Comment by jonatack** [comment] 2015-12-21 23:57
Closing as this is a duplicate of other issues and you did not supply all the info needed to reproduce (please see the CONTRIBUTING.md).

The example you show is also a little strange in that you only query for the `on_sale` attribute, but your SQL only shows `deleted_at`.

For what it's worth, the following works for me with Ransack master, Rails 5, Ruby 2.3:
```bash
[4] pry(main)> Product.ransack(active_true: '1').result.to_sql
=> "SELECT \"products\".* FROM \"products\" WHERE \"products\".\"active\" = 't'"
```

**Closed by jonatack** 2015-12-21 23:57 UTC
