### ISSUE TITLE
1.6.0 works, but master has NoMethodError: undefined method 'val'

### ISSUE THREAD

**Issue by jaredbeck** [activerecord-hackery/ransack#504] opened 2015-01-30 00:19 UTC
NoMethodError: undefined method `val' for 
    #<Arel::Nodes::Quoted:0x007fd3740118b0 @expr=nil>

This issue seems to have been introduced in 1.6.1 by https://github.com/activerecord-hackery/ransack/commit/6c59e96adaa43f4e8141352f508b84a046343591

If I *revert* the following change to `adapters/active_record/ransack/nodes/condition.rb` from said commit, then my tests pass again.

```diff
-          predicate.right.is_a?(Array) &&
-          predicate.right[0].class == Arel::Nodes::Casted
+          predicate.right[0].val.is_a?(Array)
```

Of course, I'm not suggesting we revert the change, just trying to help isolate the issue.

Stack trace:

```
NoMethodError: undefined method `val' for #<Arel::Nodes::Quoted:0x007fc1d4872678 @expr=nil>
..snip..lib/ransack/adapters/active_record/ransack/nodes/condition.rb:48:in `casted_array_with_in_predicate?'
..snip..lib/ransack/adapters/active_record/ransack/nodes/condition.rb:37:in `block in format_predicate'
..snip..lib/ransack/adapters/active_record/ransack/nodes/condition.rb:36:in `tap'
..snip..lib/ransack/adapters/active_record/ransack/nodes/condition.rb:36:in `format_predicate'
..snip..lib/ransack/adapters/active_record/ransack/nodes/condition.rb:23:in `arel_predicate_for'
..snip..lib/ransack/adapters/active_record/ransack/nodes/condition.rb:6:in `arel_predicate'
..snip..lib/ransack/visitor.rb:17:in `visit_Ransack_Nodes_Condition'
..snip..lib/ransack/visitor.rb:52:in `visit'
..snip..lib/ransack/visitor.rb:5:in `accept'
..snip..lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `block in visit_and'
..snip..lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `map'
..snip..lib/ransack/adapters/active_record/ransack/visitor.rb:4:in `visit_and'
..snip..lib/ransack/visitor.rb:24:in `visit_Ransack_Nodes_Grouping'
..snip..lib/ransack/visitor.rb:52:in `visit'
..snip..lib/ransack/visitor.rb:5:in `accept'
..snip..lib/ransack/adapters/active_record/context.rb:36:in `evaluate'
..snip..lib/ransack/search.rb:43:in `result'
.. 
.. etc. N/A
```

Relevant gems:

- arel 6.0.0
- activerecord 4.2.0 from git://github.com/rails/rails.git (at 4-2-stable)

**Comment by jonatack** [comment] 2015-01-30 11:50
Thank you @jaredbeck. Could you provide the query or test that is causing this issue?

**Comment by jaredbeck** [comment] 2015-01-30 15:36
Sure, I don't know much about ransack, but I'll try.  When I inspect the `Ransack::Search` object just prior to calling `result`, it looks like this:

```
[1] pry(#<REDACTED>)> search
=> Ransack::Search<class: REDACTED, 
base: Grouping <conditions: [
  Condition <attributes: ["REDACTED_id"], predicate: eq, values: ["something"]>, 
  Condition <attributes: ["with_unit"], predicate: in, values: ["something"]>, 
  Condition <attributes: ["REDACTED_id"], predicate: eq, values: ["something"]>, 
  Condition <attributes: ["REDACTED_id"], predicate: eq, values: ["something"]>, 
  Condition <attributes: ["REDACTED_name"], predicate: eq, values: ["something"]>, 
  Condition <attributes: ["REDACTED_id"], predicate: eq, values: ["something"]>, 
  Condition <attributes: ["REDACTED_id"], predicate: eq, values: ["something"]>
], combinator: and>>
[2] pry(#<REDACTED>)> search.result
NoMethodError: undefined method `val' for #<Arel::Nodes::Quoted:0x007fc2ae083db0 @expr=nil>
```

**Comment by jonatack** [comment] 2015-01-30 15:56
Is `REDACTED` a constant?

**Comment by jonatack** [comment] 2015-01-30 15:57
What is `REDACTED`, please?

**Comment by jonatack** [comment] 2015-01-30 15:58
Do you have a failing spec I can use to reproduce this?

**Comment by jaredbeck** [comment] 2015-01-30 16:14
> What is REDACTED, please?

To redact is to censor or obscure (part of a text) for legal or security concerns.  But, you probably knew that :)

> Do you have a failing spec I can use to reproduce this?

No, sorry, but I'm happy to give it a shot.  I don't see a spec file for `adapters/active_record/ransack/nodes/condition.rb`, and `casted_array_with_in_predicate?` is a private method.  Where would you put a test like this?  In `spec/ransack/adapters/active_record/base_spec.rb`?  Thanks!

**Comment by jonatack** [comment] 2015-01-30 16:34
@jaredbeck I don't have enough information to reproduce your issue. You have shown me a basic search query, which works and all Ransack specs pass, so your issue is coming from something else. I don't know what your `REDACTED` constant or object is, and it it likely what is causing the problem. Either that, or a search spec from you that helps to reproduce the issue (it doesn't matter right now where it should go, what matters is reproducing your issue). If no one can reproduce it, we cannot solve it and this issue will be closed because in that case it's likely not an issue with Ransack.

**Comment by jaredbeck** [comment] 2015-01-30 16:37
> If no one can reproduce it, we cannot solve it and this issue will be closed ..

Woah.  I just said I'm happy to do the legwork on a failing spec.  I think it's a bit early to shut down on me, man.  Please check out my questions about your test suite re: where the failing spec should go.

**Comment by jonatack** [comment] 2015-01-30 16:38
You wrote above that your "tests pass again". What tests, please? Give us enough to reproduce your issue.

**Comment by jonatack** [comment] 2015-01-30 16:41
`search = REDACTED.search(params[:search]).results` is not enough information to reproduce this issue. It's coming from something else in your code. Closing this until you find it or provide the info.

**Comment by jaredbeck** [comment] 2015-01-30 16:51
OK, no worries, I'll keep working on something more reproducible.  Thanks.

**Comment by jonatack** [comment] 2015-01-30 16:58
Sure. I'm happy to have another look if we can reproduce the issue.

**Comment by jaredbeck** [comment] 2015-01-30 17:00
It could be that the `Condition <attributes: ["with_unit"], predicate: in, values: ["something"]>` is the problem.  This condition comes from a param like `"with_unit_in"=>"something"`.  Naturally, the `IN` clause expects something ennumerable, not a string.  If I change the param to `"with_unit_in"=>[]`, my test passes.

Do you want ransack to be responsible for raising a helpful error when a string is provided to an `IN` clause?  I think we could provide a more helpful error than the current `NoMethodError`.  Maybe such a check could live in `Ransack::Nodes::Condition`.  Would you be interested in a PR for that?

**Comment by jaredbeck** [comment] 2015-01-30 17:03
Alternatively, a helpful check like that could be the responsibility of Arel, but that's a low-level library and they might not want to be responsible for validating inputs (read: idiot-proofing) :)

**Comment by jonatack** [comment] 2015-01-30 17:15
You may be right. A regression test to validate that hypothesis (and a helpful error message as a bonus) would be great :+1:

**Closed** 2015-01-30 23:04 UTC
