### ISSUE TITLE
Bad query when model acts_as_nested_set ( awesome_nested_set gem )

### ISSUE THREAD

**Issue by devtoro** [activerecord-hackery/ransack#548] opened 2015-06-09 10:14 UTC
Hello! 

I have a model ( Organization ) and I use the awesome_nested_set gem to give a "tree" functionality. I want to search my model, based on the parent_name field, using ransack. After a lot of searching, I decided to use a ransacker in order to accomplish that. The ransacker is the following: 

ransacker :parent_name, formatter: proc { |searching_name|
    where( name: searching_name )
    .map{ |org| org.id }.uniq
    } do |organization|
    organization.table[ :parent_id ]
  end

The query executed is the following:

"SELECT `organizations`.* FROM `organizations`  WHERE (`organizations`.`parent_id` LIKE 0)"

Here is the ransack I execute:

ransack( {:parent_name_cont=>"Crypteia", :m=>"or"}  )

How am I supposed to do this with ransack? I am stuck.. I am using ransack for all the other filters in my application, so I don't want to use custom queries or something else.

**Comment by jonatack** [comment] 2015-07-10 12:08
Hi @devtoro - This is a duplicate of previous issues for which I have provided a workaround. Have a look :) all best

**Closed by jonatack** 2015-07-10 12:08 UTC
