### ISSUE TITLE
search associations return duplicated result

### ISSUE THREAD

**Issue by warmwater** [activerecord-hackery/ransack#113] opened 2012-07-26 02:57 UTC
Hello

ransack is awesome tool, but I have one question.

I have a table A which "has_many" B, and i search A by  ":B_A_id_eq", ransack returns more than 2 records even I use result(:distinct => true), because there are more than 2 records in B which associate with same record in table A

Is there anyway to solve this problem?

Thanks 

David H

**Comment by seanfcarroll** [comment] 2017-12-29 14:39
Closed

**Comment by mortik** [comment] 2018-01-20 23:21
Why was this Issue closed? I still get duplicated results when filtering over has_many associations.

**Comment by stcho** [comment] 2018-04-03 23:16
Still getting duplicate results here as well.

**Comment by seanfcarroll** [comment] 2018-09-04 19:35
@mortik @stcho any chance you could create a repo with the issue and point it here?

**Comment by seanfcarroll** [comment] 2020-11-27 19:07
Closing. This would benefit from an example repo or better still a PR with a failing test.

**Closed by seanfcarroll** 2020-11-27 19:07 UTC

**Comment by dominiceden** [comment] 2022-06-08 09:59
Very old issue, but in my case this was caused by a sort matching multiple records e.g. multiple records shared the same `due_date` value. My solution was to add an extra sort condition to sort the records by `content` value as well:

Change
`q.sorts = ['due_date asc']`
to
`q.sorts = ['due_date asc', 'content asc']`
