### ISSUE TITLE
Problem with scopes and polymorphic associations

### ISSUE THREAD

**Issue by samstickland** [activerecord-hackery/ransack#900] opened 2018-03-28 23:28 UTC
Hi,

I'm in the progress of trying to update an old Rails application, for a local charity. Unfortunately that means some of these versions are quite old. This application was previously use the very old searchlogic.

This is with Rails 3.0.20, and Ransack 1.7.0 (which seems to be the last version that will run with Ruby 1.9.3).

I have the following setup:

```
class SupporterAction
  belongs_to :action, :polymorphic => true
  ...
end

class Donation
  has_one :supporter_action, :as => :action

  scope :with_gift_aid_declaration, conditions => { .. }
  ...
end
```

(Note that the scope does not take any parameters)

And then in the form I have:

```
<%= f.label :action_of_Donation_type_with_gift_aid_declaration, "Only covered by Gift Aid" %><  br />
<%= f.check_box :action_of_Donation_type_with_gift_aid_declaration %>
```

But I get:

```
ActionView::Template::Error:
       undefined method `action_of_Donation_type_with_gift_aid_declaration' for #<Ransack::Search:0x007f997210b3d8>
```

Any idea what the problem could be, or where I should start to look?

**Comment by samstickland** [comment] 2018-03-28 23:30
Forgot to add, I have this also in `Donation`

```
    def self.ransackable_scopes(auth_object = nil)
      [:with_gift_aid_declaration, :without_gift_aid_declaration]
    end
```

But adding a debugger statement into that method shows that it doesn't seem to be getting called.

**Comment by marcusrands** [comment] 2018-05-09 14:42
I found that the problem is related to this https://github.com/activerecord-hackery/ransack/issues/423

ransackable_scopes only work on the base object.

**Comment by seanfcarroll** [comment] 2020-11-27 19:30
Closing as resolved.

**Closed by seanfcarroll** 2020-11-27 19:30 UTC
