### ISSUE TITLE
How to construct a clickable link with a scope using Ransack and Rails

### ISSUE THREAD

**Issue by bnussey** [activerecord-hackery/ransack#515] opened 2015-02-18 18:57 UTC
Hello,

Thanks for the great gem, I am loving it. I need some help with the following, if anyone can assist, I'd be hugely appreciative. Thanks!

I have the requirement to have some scopes as clickable links in my application. This will allow the user to change the data they are seeing as required. Using Ransack and it's ransackable_scopes functionality I am very close. I do need to retain any filtering Ransack has done when the user clicks the scope.

I've got the scopes working but now I just need to construct the clickable link.

Here's my model:

    class Product < ActiveRecord::Base    

        scope :upward_trending, -> { where( "status > ?", 100).where(above_revenue_average: true).order('end_date DESC') }
    scope :downward_trending, -> { where( "status < ?", 100).order('end_date DESC') }

        def self.ransackable_scopes(auth_object = nil)
        [:upward_trending, :downward_trending]
        end
    end

Now in my view I've added these two scopes as hidden fields, like so:

            <%= search_form_for @q, :html => {:class => 'filter-form'} do |f| %>

            <div>

                <%= f.hidden_field :upward_trending %>
                <%= f.hidden_field :downward_trending %>

                <%= f.label :name_cont, "Trendosaur Search", class: 'label' %>
                <%= f.search_field :name_cont, class: 'form-control input-box', :placeholder => 'Search' %>

            </div>

            <div>

                <%= f.submit "Filter", class: 'btn btn-primary' %>
                <%= link_to "Clear Search", request.path, class:"btn btn-default" %>

            </div>
            <% end %>

From here I just need to create the links and it should work.. What is the best way to do this?

Thanks for your help!

**Comment by avit** [comment] 2015-02-20 19:15
Can't you just pass query parameters in the URL? Not really a ransack issue, but something like:

`link_to "Upward", search: {"upward_trending" => true}`

**Comment by bnussey** [comment] 2015-02-25 16:09
Hey @avit thanks so much for your response. The problem with this approach is that it doesn't maintain the existing ransack query.. any ideas? I've tried params.merge! but it has some issues with duplicating still

**Comment by avit** [comment] 2015-02-25 20:53
So if you want to merge other inputs into your button, that would need to happen client-side with JS, either make those into submit buttons which add a hidden value with the scope=true value on submit, or make your link buttons merge the form params into the href when clicked... it's a bit outside the scope of Ransack itself though.

**Comment by jonatack** [comment] 2015-03-12 04:36
Thanks @avit. Closing this issue for now since it is not a bug in Ransack.

**Closed by jonatack** 2015-03-12 04:36 UTC
