### ISSUE TITLE
Rails 5.2.1: Join type for nested relation becomes INNER, not LEFT OUTER

### ISSUE THREAD

**Issue by yhatt** [activerecord-hackery/ransack#955] opened 2018-08-20 08:47 UTC
I have tried to upgrade own Rails from 5.2.0 to 5.2.1, but several tests using ransack query to nested relation have failed because of a join type difference.

A simple example to reproduce:

```ruby
class A < ApplicationRecord
  belongs_to :b
end

class B < ApplicationRecord
  has_many :as
  has_many :cs
end

class C < ApplicationRecord
  belongs_to :b
end

# Search from A's related text `bs`.`name` or `cs`.`name`
A.ransack({ b_name_or_b_c_name_cont: 'foobar' }).result.to_sql

# Rails 5.2.0:
# SELECT "as".* FROM "as" LEFT OUTER JOIN "bs" ON "bs"."id" = "as"."b_id" LEFT OUTER JOIN "cs" ON "cs"."b_id" = "bs"."id" WHERE ("bs"."name" LIKE '%foobar%' OR "cs"."name" LIKE '%foobar%')
#                                                                         ^^^^^^^^^^
# Rails 5.2.1:
# SELECT "as".* FROM "as" LEFT OUTER JOIN "bs" ON "bs"."id" = "as"."b_id" INNER JOIN "cs" ON "cs"."b_id" = "bs"."id" WHERE ("bs"."name" LIKE '%foobar%' OR "cs"."name" LIKE '%foobar%')
#                                                                         ^^^^^
```

In Rails 5.2.1 and Ransack 2.0.1, the search query for `B`'s name will never match if `C` was not related to any records from `B`.

I don't know which one is the correct query on Rails 5.2.1, but it is sure that is losing compatible with the previous version.

**Comment by ozzyaaron** [comment] 2018-09-07 18:12
I find it hard to say anything for certain, BUT this appears to certainly be a bug. In our case we're doing a `_not_null` ransack query and so it cannot use an inner join for this type of query.

**Comment by igor04** [comment] 2018-09-15 13:47
it looks like with AR 5.2.1 and `INNER JOIN` instead of `LEFT OUTER` there is no way to have valid search results with blank associations, because inner join will reject all results without association no matter that in condition we use `or`, ex:  `own_field_or_association_field_coun` rejects records without  association even if `own_field` matches (works fine with AR 5.2.0)

**Comment by seanfcarroll** [comment] 2018-10-26 22:04
A PR with some failing tests would be super-helpful on this one.

**Comment by varyform** [comment] 2018-12-07 18:53
This seems to help: https://github.com/activerecord-hackery/ransack/compare/master...back2war:fix/rails-522

We'll battle test on prod tomorrow :)

**Comment by nguyenductung** [comment] 2018-12-13 08:14
@varyform How was your test? Do you plan to create a PR in this repository?

**Comment by dougc84** [comment] 2018-12-17 10:57
I'm updating an app from Rails 4 to 5.2.x, thus requiring an update to Ransack 2.x.  I can confirm @varyform's linked branch does seem to fix issues with improper joins (cleaning up about 40 failures) via that app's test suite.

**Comment by falcon000** [comment] 2019-01-03 08:54
Hi guys,

It seems there is a fix for this issue. Do you plan to release it in near future?

**Comment by gregmolnar** [comment] 2019-02-12 19:51
Anyone who had this issue, could you please verify that this PR fixes it? https://github.com/activerecord-hackery/ransack/pull/1004

**Comment by yhatt** [comment] 2019-02-13 02:47
@gregmolnar I thank for your great work.

Failed specs caused by join type in our app have passed with updated Rails 5.2.2 by using your branch. I also confirmed that a search query will match to nested attribute via `LEFT JOIN` correctly.

On the other hand, a simple SQL query seems to have broken join type by patching. e.g. AR's `left_joins` becomes `INNER JOIN`.

```ruby
class Foo < ApplicationRecord
  has_one :bar
end

class Bar < ApplicationRecord
  belongs_to :foo
end
```

```
# ✅ransack 2.1.1 & Rails 5.2.2
[1] pry(main)> Foo.left_joins(:bar).to_sql
=> "SELECT `foos`.* FROM `foos` LEFT OUTER JOIN `bars` ON `bars`.`foo_id` = `foos`.`id`"
                                ^^^^^^^^^^^^^^^
# gregmolnar/ransack:fix-polymorphic-joins & Rails 5.2.2
[2] pry(main)> Foo.left_joins(:bar).to_sql
=> "SELECT `foos`.* FROM `foos` INNER JOIN `bars` ON `bars`.`foo_id` = `foos`.`id`"
                                ^^^^^^^^^^
```

**Comment by gregmolnar** [comment] 2019-02-13 07:04
@yhatt thanks! I will look into it. It looks like our specs have some issues:
```
(byebug) expect(subject.send(:join_root).drop(1).map(&:join_type)).to be_all { Polyamorous::OuterJoin }
true
(byebug) subject.send(:join_root).drop(1).map(&:join_type)
[Arel::Nodes::OuterJoin, Arel::Nodes::InnerJoin]
```
That `be_all` matcher seems to be broken.

**Comment by gregmolnar** [comment] 2019-04-14 19:18
@yhatt Could you please check your app against this PR again? https://github.com/activerecord-hackery/ransack/pull/1004

**Comment by yhatt** [comment] 2019-04-22 06:25
Sorry for the delay in responding. I've tested updated PR again the all of failed tests in my app have passed as like as Rails <= 5.2.0. It seems to be fixed the wrong join type too. Thanks for your excellent work against so deep problem!

**Comment by gregmolnar** [comment] 2019-08-18 19:01
This one is resolved now I think.

**Closed by gregmolnar** 2019-08-18 19:01 UTC
Labels: Help Wanted
