### ISSUE TITLE
Ransacker with Custom Method

### ISSUE THREAD

**Issue by vigneshacker** [activerecord-hackery/ransack#520] opened 2015-03-12 14:23 UTC
I am have a method average_rating as show below.

```
def average_rating
    total = self.comments.map do |c|
      c.rating
    end.reduce(0, :+)
    total == 0 ? 0.0 : average = total/self.comments_count.to_f
  end
```

I would like to create a ransacker for the same.

```
ransacker :average_rating do |r|
    \* what to be mentioned *\
end
```

**Comment by jonatack** [comment] 2015-03-29 14:31
Stalled personal support request that is not a bug with Ransack. Closing for now.

**Comment by jonatack** [comment] 2015-03-29 14:31
Please use the issue tracker for reporting bugs in Ransack. Thanks for your understanding!

**Closed by jonatack** 2015-03-29 14:31 UTC
