### ISSUE TITLE
recent commit damages multiple database connections

### ISSUE THREAD

**Issue by mabdelfattah** [activerecord-hackery/ransack#886] opened 2018-02-26 09:17 UTC
Before this commit, it was working fine, but now I keep getting "Table not exists". I wonder why are we checking for table existence in base connection and not the connection that being used in that model.

https://github.com/activerecord-hackery/ransack/commit/d44575506ccc7cb00e618256707ed53732a07bca#r27784943

CC: @varyonic

**Comment by jsdalton** [comment] 2018-02-26 12:25
Came here to report this issue. We too are seeing these "Table not exists" errors for models that are using our other database connection.

**Comment by varyonic** [comment] 2018-02-26 13:57
Looks like a duplicate of #881.

**Comment by seanfcarroll** [comment] 2018-02-28 19:35
Hi @mabdelfattah sorry it's been causing problems with secondbase. There are sometimes issues with other gems. If you would like to help solve this could you create a small repo with the problem evident ?(even better with a failing test).

**Comment by seanfcarroll** [comment] 2020-01-10 23:26
Closed due to inactivity.

**Closed by seanfcarroll** 2020-01-10 23:26 UTC
