### ISSUE TITLE
uninitialized constant Ransack::Adapters::ActiveRecord::Associations

### ISSUE THREAD

**Issue by znz** [activerecord-hackery/ransack#527] opened 2015-03-30 08:29 UTC
I met `uninitialized constant Ransack::Adapters::ActiveRecord::Associations` at https://github.com/activerecord-hackery/ransack/blob/a8136c204514002d5627cd8574d83efa85cef8d5/lib/ransack/adapters/active_record/context.rb#L187

I think that `ActiveRecord::Associations::JoinDependency` should be `::ActiveRecord::Associations::JoinDependency`.

**Comment by jonatack** [comment] 2015-03-30 08:42
Thanks @znz! This seems like a duplicate of #526. Thanks again, appreciate the issue report :+1:

**Closed by jonatack** 2015-03-30 08:42 UTC
