### ISSUE TITLE
Rails 4.2: NoMethodError: undefined method `asc' for #<Arel::Nodes::NamedFunction...

### ISSUE THREAD

**Issue by turboladen** [activerecord-hackery/ransack#483] opened 2014-12-11 00:47 UTC
I'm in the process of upgrading a Rails 4.1.8 app to Rails 4.2.0.rc2.  I'm not seeing this behavior on 4.1.8 and I'm sure the error could be on my end, but I'm not quite sure I see a link to that.  Also, I've some wrappers (Concerns) around ransack that I'll try to unravel to simplify this report, so forgive me if things look a little funky.  Here goes...

Using MRI 2.1.0, I get the same results with master (ff0327df2c21) and the rails-4.2 branch; I've been using ransack 1.5.1 with my Rails 4.1.8 branch with success.

The backtrace for my failing specs all look similar to this:

```
Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `asc' for #<Arel::Nodes::NamedFunction:0x007ffcf0ab4a88>
     Shared Example Group: "a pageable controller" called from ./spec/controllers/zone_maps_controller_spec.rb:32
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/visitor.rb:44:in `visit_Ransack_Nodes_Sort'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/visitor.rb:52:in `visit'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/visitor.rb:5:in `accept'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/visitor.rb:13:in `block in visit_Array'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/visitor.rb:13:in `map'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/visitor.rb:13:in `visit_Array'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/visitor.rb:52:in `visit'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/visitor.rb:5:in `accept'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/adapters/active_record/context.rb:38:in `evaluate'
     # /Users/sloveless/.gem/ruby/2.1.0/bundler/gems/ransack-ff0327df2c21/lib/ransack/search.rb:42:in `result'
     # ./app/controllers/zone_maps_controller.rb:7:in `index'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/abstract_controller/base.rb:198:in `process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:117:in `call'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:117:in `call'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:151:in `call'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:169:in `call'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:169:in `call'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:169:in `call'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:169:in `block in halting'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:92:in `call'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activesupport-4.2.0.rc2/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/activerecord-4.2.0.rc2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/abstract_controller/base.rb:137:in `process'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionview-4.2.0.rc2/lib/action_view/rendering.rb:30:in `process'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/test_case.rb:629:in `process'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/test_case.rb:65:in `process'
     # /Users/sloveless/.gem/ruby/2.1.0/gems/actionpack-4.2.0.rc2/lib/action_controller/test_case.rb:505:in `get'
     # ./spec/controllers/zone_maps_controller_spec.rb:33:in `block (4 levels) in <top (required)>'
```

My controller's `#index` method:

``` ruby
  def index
    @zone_maps = ZoneMap.
                 search_with_sort(search_params, sort_params, name: 'name').result.
                 page(page).per(page_limit)

    respond_with @zone_maps,
      meta: {
        page: current_page(@zone_maps.count),
        page_count: @zone_maps.total_pages,
        total_count: @zone_maps.total_count
      }
  end
```

The `.search_with_sort` wrapper:

``` ruby
  module ModelSupport
    module RansackSearchable
      extend ActiveSupport::Concern

      included do
        if table_exists?
          columns.each do |column|
            next unless %i[string text].include? column.type

            ransacker column.name.to_sym, formatter: proc(&:downcase) do |parent|
              parent.table[column.name.to_sym].lower
            end
          end
        end

        # Uses ransack to search and sort.  Prioritizes search criteria from
        # search before sort and defaults.
        #
        # @param search [Hash] Search criteria for ransack.
        # @param sort [Hash] Sort name and direction.  Used only if search param
        #   didn't have valid criteria.
        #   example: { name: 'created_at', dir: 'desc' }
        # @param defaults [Hash] Default sort criteria if all else fails.
        #   example: { name: 'name', dir: 'asc' }
        # @return [Hash] Search params for ransack.
        def self.search_with_sort(search = {}, sort = {}, defaults = {})
          results = self.search(search)

          defaults[:dir] ||= 'asc'

          results.sorts.any?(&:valid?) || results.build_sort(sort).valid? || results.build_sort(defaults)

          results
        end
      end
    end
  end
```

Part of the controller spec:

``` ruby
  describe 'GET index' do
    it_behaves_like 'a pageable controller' do
      before { get :index }
    end
  end
```

The shared example:

``` ruby
RSpec.shared_examples 'a pageable controller' do |ivar_symbol|
  let(:assigns_symbol) do
    ivar_symbol || described_class.controller_name.to_sym
  end

  before do
    allow(subject).to receive(:page_limit) { 25 }
  end

  it 'defaults to #page_limit' do
    expect(assigns(assigns_symbol).default_per_page).to eq 25
  end

  it 'has .find result that responds to #current_page' do
    expect(assigns(assigns_symbol).current_page).to eq 1
  end

  it 'has .find result that responds to #page.size' do
    expect(assigns(assigns_symbol).page.size).to eq(assigns(assigns_symbol).count)
  end
end
```

After that, I'm not sure what other code on my end may be pertinent.  Sure smells like some changes happened in Arel...

**Comment by luckynumberslevin** [comment] 2015-01-03 09:51
It's due to the new Arel version (6.0). As I can see you call the lower method on an arel column then you try to order asc or desc. 
With previous versions you can do 
```ruby 
Order.order(Order.arel_table[:lastname].lower.desc)
# => SELECT "orders".* FROM "orders"  ORDER BY LOWER("orders"."title") DESC
```

But now with the version 6.0, you can't chain `lower` and `desc` 

I opened a ticket on arel github https://github.com/rails/arel/issues/347 , they said it is the new design, but for the moment I have no solution to solve it. If I find one, I would give it here.

**Comment by jonatack** [comment] 2015-01-04 22:06
Thanks for the input @luckynumberslevin. There are quite a few changes going on right now in Arel (which is now targeting version 7.0) and Active Record for Rails 5. When I get some time I need to get back in touch with Sean Griffin who is spearheading the API changes.

**Comment by jonatack** [comment] 2015-01-16 16:49
As per the Arel link, @luckynumberslevin solved the issue by creating a new Arel node as follows:

```ruby
Order.order(Arel::Nodes::Descending.new Order.arel_table[:title].lower)
# => SELECT "orders".* FROM "orders"  ORDER BY LOWER("orders"."title") DESC
```

**Comment by tindron** [comment] 2015-03-11 22:22
This issue still exists in ransack 1.6.3.  There don't appear to have been any changes to ransack to resolve it either.

**Comment by tindron** [comment] 2015-03-12 00:18
This issue is still present in ransack 1.6.3.  The examples at https://github.com/activerecord-hackery/ransack/wiki/Using-Ransackers show Arel::Nodes::NamedFunctions as valid to return as ransackers.  This should either be fixed or the documentation updated to indicate that Arel::Nodes::NamedFunctions can no longer be used.

**Comment by jonatack** [comment] 2015-03-12 04:07
@tindron Thanks. AFAIK anyone is free to update the wiki.

**Comment by nagyt234** [comment] 2015-06-02 15:09
I'm sorry, but I don't understand what is the solution. I'm using default sorting in controller as described in the [wiki](https://github.com/activerecord-hackery/ransack/wiki/Sorting-in-the-Controller) and I get the error mentioned in this issue. How can I set the default sorting?
Could you help? Thx.

**Comment by jembezmamy** [comment] 2016-02-15 13:00
Here is my workaround:

````ruby
# config/initializers/ransack.rb
class Arel::Nodes::NamedFunction
  include Arel::OrderPredications
end
````

The problem is that Ransack expects Arel nodes to have `asc` and `desc` methods defined, but some of them don't have these methods. A temporary solution is to include these methods in Arel node that you use in your ransacker (in my case it was `Arel::Nodes::NamedFunction`).

**Comment by seanfcarroll** [comment] 2018-02-28 19:33
Merged

**Closed by seanfcarroll** 2018-02-28 19:33 UTC
