### ISSUE TITLE
sort by model method that returns an integer

### ISSUE THREAD

**Issue by Deekor** [activerecord-hackery/ransack#690] opened 2016-06-23 18:49 UTC
I'm trying to figure out how to sort by a method on my model that returns an integer.

    class Business < ActiveRecord::Base
    
      has_many :questions
    
      def questions_count
        questions.count
      end
    end

I'd like to be able to sort by the `questions_count` method in my table using ransack.

I have tried `<th><%= sort_link @q, :questions_count %></th>` with no luck.

Is this even possible? How can I achieve it?

**Comment by stillhart** [comment] 2016-07-13 10:45
If possible, you can use a counter_cache. This also would avoid a N+1 problem which you might run into.

counter_cache:
http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache

N+1 Problem:
http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations

The problem is, to order based on you example, Ransack would need to load literally all your Busineses  from the Database, call your method and sort them based on that. This whole step should be done in the database. Imagine having millions of businesses, loading all of them each request takes forever.

**Comment by jonatack** [comment] 2016-07-13 19:24
@stillhart is right. Otherwise you could use a scope or ransacker, but it probably wouldn't be ideal. Closing this as it is not a bug report.

**Closed by jonatack** 2016-07-13 19:24 UTC
