### ISSUE TITLE
Don't know what context to use for error when both ORMs

### ISSUE THREAD

**Issue by mintuhouse** [activerecord-hackery/ransack#549] opened 2015-06-09 14:23 UTC
We use both ActiveRecord and Mongoid in our project. When I try to run ````Admin.ransack```` or any model.ransack, I get "Don't know what context to use for Admin" error.  

May be in [context.rb](https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/context.rb), we need a way to configure or automatically identify the ORM being used for that model and set context appropriately.

**Comment by ryansch** [comment] 2015-06-09 15:29
Just hit my head on this as well.  I ended up forking the gem and commenting out every line that tested for Mongoid and required in the adapters.

The ORM adapters shouldn't be monkey patching the base Context.  Context should delegate to an adapter based on the current arguments.

**Comment by mintuhouse** [comment] 2015-06-16 08:11
Duplicate of #499

**Comment by jonatack** [comment] 2015-07-05 20:32
"May be in context.rb, we need a way to configure or automatically identify the ORM being used for that model and set context appropriately."

Thanks @mintuhouse. Closing as this is a duplicate of #499 as you have noted.

I don't believe any of the maintainers use Mongoid and the PRs adding that capability were merged in with the caveat that the community would have to maintain that addition. In other words: Pull requests are welcome :smiley:

**Closed by jonatack** 2015-07-05 20:32 UTC

**Comment by jonatack** [comment] 2015-08-18 20:54
Fixed with #541.
