### ISSUE TITLE
Wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by pinkynrg** [activerecord-hackery/ransack#944] opened 2018-08-09 13:52 UTC
rails (5.2.1)
ransack (1.8.8)

```
>>  Role.first.permissions
ArgumentError: wrong number of arguments (given 3, expected 2)
	from /usr/local/rvm/gems/ruby-2.5.1/gems/polyamorous-1.3.3/lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:58:in `join_constraints'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/query_methods.rb:1027:in `build_join_query'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/query_methods.rb:1009:in `build_joins'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/query_methods.rb:929:in `build_arel'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/query_methods.rb:903:in `arel'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation.rb:554:in `block in exec_queries'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation.rb:578:in `skip_query_cache_if_necessary'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation.rb:541:in `exec_queries'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/association_relation.rb:34:in `exec_queries'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation.rb:414:in `load'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation.rb:200:in `records'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation.rb:195:in `to_ary'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/finder_methods.rb:508:in `find_take_with_limit'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation/finder_methods.rb:103:in `take'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/associations/collection_proxy.rb:291:in `take'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/relation.rb:507:in `inspect'
```

**Comment by vcsjones** [comment] 2018-08-09 13:57
Dupe of #942

**Closed** 2018-08-09 14:09 UTC

**Comment by gilcierweb** [comment] 2018-11-07 15:18
Soluction in Gemfile

```
gem 'ransack', '~> 2.1'

bundle install
```
