### ISSUE TITLE
Rails 5 IN-clause subquery

### ISSUE THREAD

**Issue by jaredbeck** [activerecord-hackery/ransack#702] opened 2016-07-22 04:15 UTC
ransack 1.8.0: In rails 4, it is possible to use a `SqlLiteral` node as the `formatter` of a custom `ransacker`. In rails 5 it is not. There may be an issue with rails 5's new attribute type system.

Consider this contrived, yet complete and executable example. The `formatter` is a subquery of `Post` ids.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # gem 'rails', '4.2.7'
  gem 'rails', '5.0.0'
  gem 'ransack', '1.8.0', require: false
  gem 'sqlite3'
end

require 'active_record'
require "ransack"
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
  ransacker(
    :banana,
    callable: -> (x) { x.table[:id] },
    formatter: ->(value) {
      ::Arel::Nodes::SqlLiteral.new(
        arel_table.project(:id).where(arel_table[:title].eq(value)).to_sql
      )
    }
  )
end

class BugTest < Minitest::Test
  def test_association_stuff
    a = Post.create!(title: 'apple')
    b = Post.create!(title: 'banana')
    c = Post.create!(title: 'coconut')

    # rails 4 passes. query is:
    # SELECT "posts".* FROM "posts" WHERE "posts"."id" IN (
    #   SELECT id FROM "posts" WHERE "posts"."title" = 'banana'
    # )

    # rails 5 fails. query is:
    # SELECT "posts".* FROM "posts" WHERE "posts"."id" IN (0)

    assert_equal [b], Post.ransack(banana_in: "banana").result
  end
end
```

I know there are better ways to use ransack to search post titles :) as I said, this is a contrived example.

**Comment by jonatack** [comment] 2016-07-30 13:01
Reproduced. On Rails 5.0.0 and master (5.1.0.alpha) too.

**Comment by jonatack** [comment] 2016-07-30 13:04
With both Ransack 1.8.1 (latest release) and also 1.7.0 from a year ago.

**Comment by jonatack** [comment] 2016-07-30 13:13
@jaredbeck This appears to be coming from a change in Arel or Active Record, not Ransack. You might need to formulate the Arel query differently. Closing for now unless this is a bug in Ransack.

**Closed by jonatack** 2016-07-30 13:13 UTC

**Comment by jonatack** [comment] 2016-07-30 13:14
@jaredbeck This appears to be coming from a change in Arel or Active Record between Rails 4 and 5, not a bug in Ransack. It's a bit of a strange example. You might need to formulate the Arel query differently. Closing for now unless this is a bug in Ransack.

This works fine:

```ruby
Post.ransack(title_in: 'banana').result
```

**Comment by jaredbeck** [comment] 2016-08-08 19:40
>> I know there are better ways to use ransack to search post titles :) as I said, this is a contrived example.

> P.S. - This works fine, though I imagine you are trying to do something else:
> Post.ransack(title_in: 'banana').result

Correct, my admittedly contrived example does not require an IN-clause subquery. My app does.

> You might need to formulate your Arel query differently. Ransackers just provide a conduit to Arel. The Rails team has clarified over the past couple years that Arel methods are :nodoc: and likely to change without warning.

Yeah, my colleagues keep writing complicated custom ransackers that break every time I upgrade arel. Maybe there should be a warning about this in the custom ransacker docs. Would you like a PR with such a warning?

**Comment by jonatack** [comment] 2016-08-08 21:11
There might be news from the front. If I recall @sgrif's remarks in the
latest bikeshed.fm podcast #74 discussing Ransack and Arel -- and I could
be wrong -- the Arel API is planned to stabilize and return from :no
doc: back to public. Yay! -- to symbolically celebrate I added Sean's
vintage Arel blog post to the two other Arel resources in the Ransack wiki
today.

PR: There is already a warning in the ransackers section of the wiki about
complicated Arel ransackers not being a cure-all with mention of
a few alternate solutions, so I think we're fine.

On the other hand, any of the TODO or FIXME comments in the code base would
be wonderful PRs to work on.

**Comment by jaredbeck** [comment] 2016-08-08 21:24
> .. news from the front.

🎺 🎵📰! 😀 

> .. the Arel API is planned to stabilize and return from `:nodoc:` back to public ..

That's great news, thanks.
