### ISSUE TITLE
Searching across multiple associations that reference the same model/table joining on the wrong association

### ISSUE THREAD

**Issue by jhdavids8** [activerecord-hackery/ransack#374] opened 2014-05-14 04:18 UTC
Hi all!

Let's say I have a model such as:

```
class Recommendation < ActiveRecord::Base
  belongs_to :user
  belongs_to :target_user, class_name: 'User'
end
```

Now, say my Ransack search filters looks like this (as JSON, as I'm using Ransack with a REST API. Hopefully, it's more readable):

```
q: {
  user: {
    job_title: { 
      eq: "Designer"
    }
  },
  target_user: {
    group: {
      name: {
        eq: "Design"
      }
    }
  }
}
```

When I was on Rails 4.0.2 and Ransack 1.2.1, this was the SQL output I received:

```
"SELECT \"recommendations\".* FROM \"recommendations\" 
LEFT OUTER JOIN \"users\" ON \"users\".\"id\" = \"recommendations\".\"user_id\" 
LEFT OUTER JOIN \"users\" \"target_users_recommendations\" ON \"target_users_recommendations\".\"id\" = \"recommendations\".\"target_user_id\" 
LEFT OUTER JOIN \"groups\" ON \"groups\".\"id\" = \"target_users_recommendations\".\"department_id\" 
WHERE ((\"users\".\"job_title\" = 'Designer' AND \"groups\".\"name\" = 'Design'))"
```

Notice how the group is joined here (4th line, last LEFT OUTER JOIN).

However, after upgrading to Rails 4.1.1 and the Ransack 4.1 branch, this is the SQL output, which is wrong, as notice now how the group is joined (it's joined on the first user association, not the target user association).

```
"SELECT \"recommendations\".* FROM \"recommendations\"
LEFT OUTER JOIN \"users\" ON \"users\".\"id\" = \"recommendations\".\"user_id\" 
LEFT OUTER JOIN \"users\" \"target_users_recommendations\" ON \"target_users_recommendations\".\"id\" = \"recommendations\".\"target_user_id\" 
LEFT OUTER JOIN \"groups\" ON \"groups\".\"id\" = \"users\".\"department_id\" 
WHERE ((\"users\".\"job_title\" = 'Designer' AND \"groups\".\"name\" = 'Design'))"
```

This is consistent across several specs I have failing at the moment. Any query on an association for the second user association will fail, as it joins on the former user association. 

Hopefully this is enough to get you guys started, but if not, please let me know. I'm going to try and find some time to dig deeper myself. Thanks!

**Comment by clammers** [comment] 2015-01-02 11:56
Issue also occured in rails 4.2 with ransack 1.5.1. Fix would be great!

**Comment by yairlev** [comment] 2015-01-16 23:30
Same issue with rails 4.1.0 and ransack 1.6.2

**Comment by Sitch** [comment] 2015-03-24 15:48
Same issue with rails 4.1.8 and ransack 1.6.4, 4.1 branch, and current master branch

**Comment by jonatack** [comment] 2015-03-25 09:27
@jhdavid8 thanks for the regression test, which is the first step toward a fix :+1: 

Everyone else: Thanks for the reports, but **you need to provide a test or use someone's test like @jhdavids8's** and state that, showing its output, otherwise your report is not useful because not precisely reproducible and testable. You need to begin with, and show, a failing test.

I merged @jhdavids8's spec into Ransack and can confirm that it passes in Rails 4-0-stable, but not in 4-1-stable, 4-2-stable and 5.0.0.alpha / master. Here is the output when the spec fails:

```bash
∴ DB=PostgreSQL bundle exec rake spec
===================================================================================
Running specs against PostgreSQL, Active Record 5.0.0.alpha and Arel 7.0.0.alpha...
===================================================================================
...................................................................................
...................................................................................
....................................................................F..............
.....

Failures:

1) Ransack::Search#result evaluates conditions for multiple belongs_to associations
to the same table contextually

expected:
"SELECT \"recommendations\".* FROM \"recommendations\"
LEFT OUTER JOIN \"people\" ON \"people\".\"id\" = \"recommendations\".\"person_id\"
LEFT OUTER JOIN \"people\" \"target_people_recommendations\"
  ON \"target_people_recommendations\".\"id\" = \"recommendations\".\"target_person_id\"
LEFT OUTER JOIN \"people\" \"parents_people\"
  ON \"parents_people\".\"id\" = \"target_people_recommendations\".\"parent_id\"
WHERE ((\"people\".\"name\" = 'Ernie' AND \"parents_people\".\"name\" = 'Test'))"

got: 
"SELECT \"recommendations\".* FROM \"recommendations\"
LEFT OUTER JOIN \"people\" ON \"people\".\"id\" = \"recommendations\".\"person_id\"
LEFT OUTER JOIN \"people\" \"target_people_recommendations\"
  ON \"target_people_recommendations\".\"id\" = \"recommendations\".\"target_person_id\"
LEFT OUTER JOIN \"people\" \"parents_people\"
  ON \"parents_people\".\"id\" = \"people\".\"parent_id\"
WHERE (\"people\".\"name\" = 'Ernie' AND \"parents_people\".\"name\" = 'Test')"

# ./spec/ransack/search_spec.rb:220:in `block (3 levels) in <module:Ransack>'
```

**Comment by jonatack** [comment] 2015-03-25 09:36
Will push it to Ransack master to help anyone who wants/needs to fix this issue.

Fork Ransack to your repo, open the file `ransack/spec/ransack/search_spec.rb`, uncomment the test beginning at line 220, and set the Rails version you'd like to test the Ransack Gemfile (i.e. '4-1-stable', '4.2.1', etc). Then, in the console, run `bundle install`, then `bundle exec rake spec`.

**Comment by jonatack** [comment] 2015-03-25 10:21
Pushed the spec to Ransack master to help anyone who wants/needs to fix this issue.
Steps:

- Fork Ransack to your repo 

- Open the file `ransack/spec/ransack/search_spec.rb` and uncomment the test beginning at line 221

- Set the Rails version you'd like to test in ransack's Gemfile ('4-1-stable', '4.2.1', etc.)

- In the console, run `bundle install`, then `bundle exec rake spec` to run the tests

- Write a fix that makes the test pass!

- Send a PR :smiley:

**Comment by jonatack** [comment] 2015-03-25 10:42
The fix might be related to Rails issue [#19276](https://github.com/rails/rails/issues/19276) and Rails PR [#19442](https://github.com/rails/rails/pull/19452).

**Comment by jonatack** [comment] 2015-03-29 05:29
There is also this: https://github.com/rails/rails/issues/19427#issuecomment-87321631

**Comment by linkyndy** [comment] 2015-04-14 12:35
Here's yet another gist related to this issue: https://gist.github.com/linkyndy/e84534e1cdc19dd8e4cc

I've posted it just to raise awareness of this bug :)

**Comment by Sitch** [comment] 2015-04-14 13:19
Looks like it's not properly referencing a table alias.  You can see a diff from the two AST's here:
https://www.diffchecker.com/1d3kkrjq

**Comment by bertBruynooghe** [comment] 2015-04-30 16:34
FYI: I was able to work around the issue of @linkyndy by defining an extra association ```has_one :master_party, through: :master_client, source: :party``` and use ```Client.ransack(master_party_name_cont: 'arty')``` instead.
I guess the issue of @jhdavids8  could also be worked around by creating a ```target_group``` associaton, and using that in the ransack expression.

**Comment by Sitch** [comment] 2015-04-30 16:53
The main reason for these issues is the Rails 4.1 code transitioning from matching joins on JoinAssociations to JoinDependencys (which have their own AliasTracker that is not coalesced with other JoinDependency's AliasTrackers).  I am not sure if this is a active design decision on the part of the Rails team, but for a patch on the Ransack side, we would need to build a singular (correctly aliased) JoinDependency (or monkeypatch the Rails code to support attaching JoinAssociations

**Comment by harssh** [comment] 2015-06-26 17:37
Hi 
Is this issue fixed or any work around for this.

**Comment by bertBruynooghe** [comment] 2015-06-30 14:12
I worked around the issue by dynamically creating the necessary associations in a Rails initialiser (code [here](https://github.com/UP-nxt/upnxt-ransack/blob/master/config/initializers/ransack.rb)). It might be an idea to fix the issue by relying on a more stable Rails API?

Any ideas on possible side effects of this patch are highly appreciated.

**Comment by seanfcarroll** [comment] 2020-01-10 23:32
Closed due to age

**Closed by seanfcarroll** 2020-01-10 23:32 UTC
